name: release
on:
  push:
    branches:
      - "v*"

jobs:
  build:
    strategy:
      matrix:
        # Use these Java versions
        java: [
          21,    # Current Java LTS
        ]
    runs-on: ubuntu-22.04
    steps:
      - name: checkout repository
        uses: actions/checkout@v4
      - name: validate gradle wrapper
        uses: gradle/wrapper-validation-action@v2
      - name: setup jdk ${{ matrix.java }}
        uses: actions/setup-java@v4
        with:
          java-version: ${{ matrix.java }}
          distribution: 'microsoft'
      - name: make gradle wrapper executable
        run: chmod +x ./gradlew
      - name: Extract version from branch name
        env:
          REF: ${{ github.ref }}
        run: |
          BRANCH_NAME=${REF#refs/heads/}
          version=${BRANCH_NAME#v}
          echo "RELEASE_VERSION=$version" >> $GITHUB_ENV
      - name: update version
        run: |
          BRANCH=v${RELEASE_VERSION}
          git config --local user.name "GitHub Actions"
          git config --local user.email "actions@github.com"
          git checkout $BRANCH
          sed -i "s/mod_version=0.0.0/mod_version=${RELEASE_VERSION}/" gradle.properties
          git add gradle.properties
          git commit -m "update version"
          git push
      - name: build
        run: ./gradlew build
      - name: capture build artifacts
        if: ${{ matrix.java == '21' }} # Only upload artifacts built from latest java
        uses: actions/upload-artifact@v4
        with:
          name: Artifacts
          path: build/libs/
      - name: release
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "v${{ env.RELEASE_VERSION }}"
          prerelease: false
          files: |
            build/libs/anti-anti-afk-${{ env.RELEASE_VERSION }}.jar